### ISSUE TITLE
Yaml defined applications not provisioned when Synced Folder is not empty

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/cakebox-console#65]
Real bug, not working as designed. Reproducable using a yaml with:

```yaml
synced_folders:
  - local:  /git/mycake3.app
    remote: /var/www/mycake3.app

apps:
  - url: mycake3.app
    options: --path /var/www/mycake3.app
```

1. create content in local folder
2. ``vagrant reload --provision``
3. Application provisioning will skip installing mycake3.app with ``Directory did not pass readiness test`` message
